### ISSUE TITLE
[CRITICAL]: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk

### ISSUE THREAD

**Issue by MathBunny** [MathBunny/strava-wind-analysis#106]
Received user feedback regarding intermittent outages with similar symptoms as #105. However, after running `lsblk` and `df -h`, it seems that disk space is not an issue.

By checking the logs, the following is found:
```
ReplyError: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error.
    at parseError (/home/ubuntu/stravawindanalysis-backend/node_modules/redis-parser/lib/parser.js:193:12)
    at parseType (/home/ubuntu/stravawindanalysis-backend/node_modules/redis-parser/lib/parser.js:303:14)
events.js:480
    return emitter.listenerCount(type);
                   ^

RangeError: Maximum call stack size exceeded
    at Function.EventEmitter.listenerCount (events.js:480:20)
    at Domain._errorHandler (domain.js:112:22)
    at process._fatalException (bootstrap_node.js:326:33)
    at Domain._errorHandler (domain.js:145:26)
    at process._fatalException (bootstrap_node.js:326:33)
    at Domain._errorHandler (domain.js:145:26)
    at process._fatalException (bootstrap_node.js:326:33)
    at Domain._errorHandler (domain.js:145:26)
    at process._fatalException (bootstrap_node.js:326:33)
    at Domain._errorHandler (domain.js:145:26)

```

**Comment by MathBunny** [comment]
After further inspection, it seems that the Redis background saving schemes leverages copy-on-write semantics of the fork syscall where the child process has the same copy of the parent, but the pages are duplicated only when changes occur. However, `overcommit_memory` was not set to `1` and instead `2`, which according to [this](https://www.kernel.org/doc/Documentation/vm/overcommit-accounting) results in the behavior of having sufficient RAM but it not being used properly. Redis would attempt to fork the process and there wouldn't be enough memory to fulfill the syscall if all pages were duplicated. Now, byt setting the value to `1` it should be fine as pages will be consolidated as-required effectively more fully exhausting the available RAM.

Resolved by running:
> sysctl vm.overcommit_memory=1
